### ISSUE TITLE
web version

### ISSUE THREAD

**Issue by reslear** [Cap-go/capacitor-social-login#16]
By the way, any plans for a web version and implementation method?

we can discuss (p.s. maybe need GH discussions) the stack for example: 

- for facebook https://developers.facebook.com/docs/javascript/quickstart/. 
- for Google Identity Services is deprecated, need to use https://developers.google.com/privacy-sandbox/cookies/fedcm. 
but maybe it's too early.
- apple https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js

Or not to implement at all, but to propose examples and recommendations for frameworks/libs. I don't use web versions for a long time already, use ready solutions, for example https://github.com/wavezync/vue3-google-signin/tree/main through conditions 

```ts
if (Capacitor.isNativePlatform()) {
  // auth for ios/andoid 
} else {
  // auth for pwa
}
```

**Comment by WcaleNieWolny** [comment]
I think web could happen, although for Apple it requires a backend server, so I am not sure how easy that would be to setup given the plethora of frameworks out there.

As for google, I am sure we could figure something out. I did google login on the web once.

Facebook wise, I have no idea. Anything related to facebook is better suited for @riderx. I haven't worked on facebook

**Comment by reslear** [comment]
Cześć, about apple

There is nothing wrong with it, as it should work in combination with the backend. By the way, your implementation is complicated. 

I would recommend using https://github.com/a-tokyo/apple-signin-auth with couple  line of code: 

```ts
import appleSignin from 'apple-signin-auth'
await appleSignin.verifyIdToken(idToken) 
```


it is highly recommended to add a link to the detailed guide. 

https://github.com/capacitor-community/apple-sign-in/issues/48#issuecomment-1024936348

**Comment by WcaleNieWolny** [comment]
Yeah, I can see a web version getting implemented in the future, but I cannot give an ETA

**Comment by riderx** [comment]
@reslear feel free to work on it :)
We welcome contributions you have already the definition

**Comment by WcaleNieWolny** [comment]
Martin has assigned me the task of implementing the web version. I will try to implement it.

**Comment by riderx** [comment]
@reslear You can try now Apple and Google been added with latest SDK, Facebook will come later :)
