### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by AirGoatOne** [Cap-go/capacitor-social-login#38]
Hi,

I am interested in using this plugin in one of my project. I have searched for license info in the repo but I can't find it in the usual locations.

Adding the license the project is published under would help me to know if using this plugin is an option.

Could you add license info into the repo?

Thanks!

**Comment by WcaleNieWolny** [comment]
I believe that @riderx has the sole power to decide on the license.

Thank you for bringing this issue to our attention
