### ISSUE TITLE
idToken is not returned in the response (0.0.68-alpha.2)

### ISSUE THREAD

**Issue by glitchcodes** [Cap-go/capacitor-social-login#54]
The Android version doesn't return the idToken in the response because it is commented out, I am using that token to validate oauth requests from my backend.
https://github.com/Cap-go/capacitor-social-login/blob/d3d316e1c361d10bb66204e42664a5ddae4acafa/android/src/main/java/ee/forgr/capacitor/social/login/GoogleProvider.java#L220

I know that this is an development version but the stable branch doesn't have the fixes for web version and this development branch works perfectly fine if idToken is returned in the response

**Comment by WcaleNieWolny** [comment]
This is a change that was introduced on purpose and I will not be reverting it. Providing an `idToken` is impossible on all the platforms (it's possible on Android + iOS, but it is not possible on the web).

As a result of this very frustrating limitation I and @riderx have both decided that it would be for the better to remove it entirely and replace it with `accessToken`

You said that you use `idToken` to perform some backend validation. You are sill able to do backend validation with the `accessToken`. Please see [the documentation](https://github.com/Cap-go/capacitor-social-login/blob/development/docs/setup_google.md#an-example-backend-for-online-access)
