### ISSUE TITLE
Google Android : Activity is cancelled by the user 

### ISSUE THREAD

**Issue by AntoineAwaida** [Cap-go/capacitor-social-login#55]
Hi, first of all thanks for all the hard work !

I get this error even though **i am using my web ClientId when initializing**.

```
const response = await SocialLogin.login({
      provider: 'google',
      options: {
        scopes: ['profile', 'email'],
      },
    });
````

yields this `activity is cancelled by the user error`.  Any thoughts ?

**Comment by WcaleNieWolny** [comment]
Hi, first, please tell me which version and what platform are you currently using.

Please attempt to use `0.0.68-alpha.2` (the development version) and please also make sure that you [have followed the docs](https://github.com/Cap-go/capacitor-social-login/blob/development/docs/setup_google.md#using-google-login-on-android)

**Comment by AntoineAwaida** [comment]
Hi, 
I tried to use `0.0.68-alpha.2` but no better luck. I use capacitor 6.1.2 -I am attempting to migrate from the `codetrix-studio` package due to the Apple privacy requirements on the 12th. 

I followed the docs - apart from the fact that I am unable to copy paste the MainActivity code part (imports are missing, `Intent` type is indicated as wrong, etc), everything seems fine.

**Comment by WcaleNieWolny** [comment]
Wait, I am confused. The `MainActivity` changes are critical for the plugin to work.
Personally, this is how my `MainActivity` looks:
```java
package me.wcaleniewolny.io.ionic.starter.capgo.google.login;

import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.util.Log;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginHandle;

import ee.forgr.capacitor.social.login.GoogleProvider;
import ee.forgr.capacitor.social.login.SocialLoginPlugin;

public class MainActivity extends BridgeActivity {

    @Override
    protected void onNewIntent(Intent intent) {
    String action = intent.getAction();
        Uri data = intent.getData();

        if (Intent.ACTION_VIEW.equals(action) && data != null) {
            PluginHandle pluginHandle = getBridge().getPlugin("SocialLogin");
            if (pluginHandle == null) {
                Log.i("Apple Login Intent", "SocialLogin login handle is null");
                return;
            }
            Plugin plugin = pluginHandle.getInstance();
            if (!(plugin instanceof SocialLoginPlugin)) {
                Log.i("Apple Login Intent", "SocialLogin plugin instance is not SocialLoginPlugin");
                return;
            }
            ((SocialLoginPlugin) plugin).handleAppleLoginIntent(intent);
            return;
        }
        super.onNewIntent(intent);
    }


    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && requestCode >= GoogleProvider.REQUEST_AUTHORIZE_GOOGLE_MIN && requestCode < GoogleProvider.REQUEST_AUTHORIZE_GOOGLE_MAX) {
            PluginHandle pluginHandle = getBridge().getPlugin("SocialLogin");
            if (pluginHandle == null) {
                Log.i("Google Activity Result", "SocialLogin login handle is null");
                return;
            }
            Plugin plugin = pluginHandle.getInstance();
            if (!(plugin instanceof SocialLoginPlugin)) {
                Log.i("Google Activity Result", "SocialLogin plugin instance is not SocialLoginPlugin");
                return;
            }
            ((SocialLoginPlugin) plugin).handleGoogleLoginIntent(requestCode, data);
        }
    }
}
```

Can you please share the error?

**Comment by AntoineAwaida** [comment]
Ok it works well now I've updated the SHA fingerpint !! I didn't suspect this as it was already setup for my deployed app (but differently ? )...

**Comment by WcaleNieWolny** [comment]
I am glad that it works, can you share what did not work for your for the main activity changes?

I believe that it is important for me to improve the docs if there is some problem there

**Comment by AntoineAwaida** [comment]
<img width="1512" alt="Screenshot 2024-11-10 at 12 02 10" src="https://github.com/user-attachments/assets/2e3c2c29-b657-428f-8d85-c07dcf03bb2d">

by the way i didn't add that part and it still works - is this expected ?

**Comment by WcaleNieWolny** [comment]
Yeah, the imports are something I will add.

Could you run `npx cap sync` and see if the issue persists?

**Comment by AntoineAwaida** [comment]
Yes it still persists !

**Comment by WcaleNieWolny** [comment]
Just to confirm, you are using `0.0.68-alpha.2` right now? Or are you using `0.0.67`

**Comment by AntoineAwaida** [comment]
yes i am using the alpha2!

**Comment by WcaleNieWolny** [comment]
Ah, I see. The changes to main activity are only required for `0.0.68-alpha.2` release of this plugin.
`0.0.68` is the release from the `main` branch and not the [development branch](https://github.com/Cap-go/capacitor-social-login/tree/development). Main does not have the changes to the google provider.

I sent you the docs from the `development` branch. If you were to use `0.0.68-alpha.2` you would have to implement the changes to `MainActivity`
