### ISSUE TITLE
Sign in with Apple - Private Relay Email

### ISSUE THREAD

**Issue by DrBeza** [Cap-go/capacitor-social-login#67]
Hi there,

Thanks for the work on this plugin. 

I was implementing Apple Id into my capacitor app and passing "email" and "profile" scopes.

If I choose to share my email then "email" comes through. 

However if I pick the hide my email it shows a private relay email address - e.g. ****@privaterelay.appleid.com but then the "email" field is empty.

I'm not sure this is the expected behaviour or an issue?

**Comment by piotr-cz** [comment]
The email value is never empty when using `@capacitor-community/apple-sign-in` package.
It's either real email or `xxxxxxxxxx@privaterelay.appleid.com`

**Comment by DrBeza** [comment]
I'm not seeing this behaviour with `"@capgo/capacitor-social-login": "^0.0.68-alpha.8",`. I have also tried `0.0.68` previously.

I just tried this now on a fresh simulator device running iPhone 16 (18.1). 

I will try to test this against a real device next week in case the simulator is the problem.

```
        await SocialLogin.initialize({
            apple: {},
        });

        const response = await SocialLogin.login({
            provider: 'apple',
            options: {
                scopes: ['email', 'profile'],
            },
        });

        console.log(JSON.stringify(response));
```

My response from `login` is:

```{"result":{"idToken":"<removed>","accessToken":{"token":"<removed>"},"profile":{"givenName":"<removed>","familyName":"<removed>","user":"<removed>","email":""}},"provider":"apple"}```

As I mentioned in the first post if I select to allow my email, then email is populated.

Here are the lines I'm seeing in the App log:

```
⚡️  To Native ->  SocialLogin initialize 42571992
No saved state found
⚡️  TO JS undefined
⚡️  To Native ->  SocialLogin login 42571993
Successfully saved user info locally
Apple persistState: {"refreshToken":"","idToken":"<removed>","accessToken":""}
⚡️  TO JS {"result":{"idToken":"<removed>","accessToken":{"token":"<removed>
⚡️  [log] - {"result":{"idToken":"<removed>","accessToken":{"token":"<removed>"},"profile":{"givenName":"<removed>","familyName":"<removed>","user":"<removed>","email":""}},"provider":"apple"}
```

**Comment by DrBeza** [comment]
This appears to be working as stated on a real phone. 

I am guessing using the simulator was the problem here.
