### ISSUE TITLE
[Android] Google sign in fails with: Cannot find an eligible account.

### ISSUE THREAD

**Issue by solartune** [Cap-go/capacitor-social-login#74]
Hey folks, this might not be the plugin's issue but maybe someone faced it before.
I support both ios and android platforms of my app and trying to add sign-in with Google now.
It works perfectly on ios but android doesn't work with one of the accounts I use for testing.
So I have account A and account B. When I add account A to an android phone and press the login button - nothing happens. The dialog box for choosing a Google account for signing in simply doesn't appear.
When I add account B to the phone and press the login button - the dialog box does appear and I can sign in with either of the two.
If I remove account A and try only with B, it also works.
So there is something wrong with account A but I cannot figure out what exactly. Also, the same account A works on ios without issues.

And that's what I see in the logs when I'm trying to log in with that account:
`androidx.credentials.exceptions.NoCredentialException: During get sign-in intent, failure response from one tap: 16: Cannot find an eligible account.`

Do you have any ideas on what to check? I went through the security settings of the account and anything else that I thought could potentially affect it but the result is the same.

It's also interesting, that when having both accounts on the phone I can sign in with account A without any problem.

This is preventing me from releasing the feature to production as I'm not sure how many people will face this problem 🤔

**Comment by WcaleNieWolny** [comment]
If I were you, I would try the [development version](https://github.com/Cap-go/capacitor-social-login/tree/development).

This is essentially a fork of the main branch with fixes for Google Login + some extra features.

**Comment by solartune** [comment]
I think I started with 0.0.68 and the latest I tried is 0.0.76.

I'll try the development version and report back. Thanks!

**Comment by WcaleNieWolny** [comment]
Keep in mind that the development version has different requirements for setup. Please follow the setup guide **FROM** the development guide. It's **REALLY** important

**Comment by solartune** [comment]
Hey @WcaleNieWolny, I just tried the dev version (`0.0.69-alpha.9` to be specific) and it worked!

When do you think there will be a more stable version of it?

Also, I had to adapt the code specified in the setup guide for `MainActivity.java` as Android Studio was complaining about a few things. 
Here is the version that worked for me but I'm not sure how correct it is (never worked with Java before):
```
package my.app;

import com.getcapacitor.BridgeActivity;
import ee.forgr.capacitor.social.login.GoogleProvider;
import ee.forgr.capacitor.social.login.SocialLoginPlugin;
import android.content.Intent;
import com.getcapacitor.PluginHandle;
import android.util.Log;

public class MainActivity extends BridgeActivity {

  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if (requestCode >= GoogleProvider.REQUEST_AUTHORIZE_GOOGLE_MIN && requestCode < GoogleProvider.REQUEST_AUTHORIZE_GOOGLE_MAX) {
        PluginHandle pluginHandle = getBridge().getPlugin("SocialLogin");
        if (pluginHandle == null) {
            Log.i("Google Activity Result", "SocialLogin login handle is null");
            return;
        }
        SocialLoginPlugin plugin = (SocialLoginPlugin) pluginHandle.getInstance();
        if (!(plugin instanceof SocialLoginPlugin)) {
            Log.i("Google Activity Result", "SocialLogin plugin instance is not SocialLoginPlugin");
            return;
        }
        ((SocialLoginPlugin) plugin).handleGoogleLoginIntent(requestCode, data);
    }
  }
}
```

What do you think?

**Comment by WcaleNieWolny** [comment]
The code looks good, I don't think that `development` will get merged into main any time soon. It's stable, as I tested it extensively (way more than the current main).

Development might get merged in months into the main branch

**Comment by solartune** [comment]
Thanks @WcaleNieWolny!
I just tested it on ios and Google Sign-in doesn't work there for some reason 🤔 It did work before and I didn't change this part of the code after installing the dev version. I've also gone through the setup guide for Google on ios (related to the dev branch) and didn't spot any differences with what I already did previously.
Nothing was changed in the Google Play Console either.

Oh and the error I'm getting is:
`Error: Response could not be decoded because of error: The data couldn’t be read because it is missing.`

So it looks like it's not getting the data from Google for some reason? Testing it on a simulator if that makes any difference.

**Comment by WcaleNieWolny** [comment]
> Testing it on a simulator if that makes any difference

I do not know if it makes a difference, personally I have every only tested on a physical device
Also, yes - you would be correct in saying that iOS doesn't have any differences between setup on development and main.

My best advise would be to clean the data of the app (uninstall it) and reinstall it. The error that you provided doesn't tell me much, and without reproducible steps I am not able to assist and debug this issue further

**Comment by solartune** [comment]
Alright, for some reason it doesn't work on the simulator but worked when I uploaded it to TestFlight and installed on my phone.
Closing the issue now and thanks again for all your help! 🙂
