### ISSUE TITLE
AccessToken.UserId incorrect

### ISSUE THREAD

**Issue by co-dax** [Cap-go/capacitor-social-login#77]
AccessToken.UserId is defined in types but the actual access token object is only having AccessToken.User**ID**. Notice the "ID" part is capital letters.
This is the case of Facebook provider.

**Comment by riderx** [comment]
We updated it in last version 
![CleanShot 2024-12-10 at 18 18 08](https://github.com/user-attachments/assets/dab844c0-d8d0-4c5e-8fc7-e9fa05eb510b)
do this is good for you?

**Comment by co-dax** [comment]
Thanks!
